# .github/workflows/deploy.yml

name: 'Terragrunt Deploy'
  
on:
  push:
    paths:
      - '.github/**'
      - 'infra/**'
      - 'src/**'
      - 'justfile'
   
jobs:
  Pre-check:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'

  Build-Rust-Lambdas:
    name: 'Build Rust Lambdas'
    needs: Pre-check
    uses: fomiller/gh-actions/.github/workflows/rust-lambda.yaml@main
    with:
      lambda_dir: src/
      lambda_output:  infra/modules/aws/lambda/bin/
      artifacts_dir: infra/modules/aws/lambda/bin
      cache_file: Cargo.lock
      # conditionally build lambdas if these files change
      src-filters: |
        lambda:
          - 'src/**'
          - 'infra/**'
            
  Deploy-infra:
    name: 'Deploy Infra'
    needs: [Pre-check, Build-Rust-Lambdas]
    uses: fomiller/gh-actions/.github/workflows/terragrunt.yaml@main
    with:
      environment: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref) && 'prod' || 'dev' }}
      infra-dir: infra/modules/aws
      doppler-project: dungeons-and-discord
      download-artifacts: true
      artifacts_dir: infra/modules/aws/lambda/bin
    secrets: inherit
     
    
    # use if you need to debug workflow
    # - name: DEBUG
    #   uses: lhotari/action-upterm@v1
    #   with:
    #       limit-access-to-actor: true
    #       limit-access-to-users: Fomiller

